# Generated by Django 3.0.7 on 2021-04-14 13:39

import apps.entity.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0014_auto_20210414_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Vacuna')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Vacuna')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('date', models.DateField(verbose_name='Fecha Creacion')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Pet', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Vacunacion',
                'verbose_name_plural': 'Vacunaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Parasite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Desparasitante')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Desparasitante')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('date', models.DateField(verbose_name='Fecha Creacion')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Pet', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Desparasitacion',
                'verbose_name_plural': 'Desparasitaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('motive', models.CharField(max_length=30, verbose_name='Motivo')),
                ('symptom', models.CharField(max_length=60, verbose_name='Sintomas')),
                ('temperature', models.FloatField(default=0, verbose_name='Temperatura')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('date_c', models.DateField(verbose_name='Fecha Creacion')),
                ('date_u', models.DateField(auto_now=True, verbose_name='Fecha Actualizacion')),
                ('diag_pre', models.CharField(blank=True, max_length=50, null=True, verbose_name='Diagnostico preventivo')),
                ('diag_def', models.CharField(blank=True, max_length=50, null=True, verbose_name='Diagnostico definitivo')),
                ('fre_car', models.FloatField(blank=True, default=0, null=True, verbose_name='Frecuencia cardiaca')),
                ('fre_res', models.FloatField(blank=True, default=0, null=True, verbose_name='Frecuencia respiratoria')),
                ('examination', models.CharField(blank=True, max_length=50, null=True, verbose_name='Examen')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Pet', verbose_name='Paciente')),
            ],
            options={
                'verbose_name': 'Consulta',
                'verbose_name_plural': 'Consultas',
                'ordering': ['id'],
            },
        ),
    ]
