# Generated by Django 3.0.7 on 2021-04-12 11:11

import apps.entity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='Cedula')),
                ('gender', models.CharField(choices=[('male', 'Masculino'), ('female', 'Femenino')], max_length=15)),
                ('type_name', models.CharField(choices=[('V-', 'V-'), ('J-', 'J-'), ('E-', 'E-')], default='V-', max_length=10)),
                ('first_name', models.CharField(max_length=40, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion Habitacional')),
                ('co_mobile', models.CharField(blank=True, choices=[('0412', '0412'), ('0416', '0416'), ('0426', '0426'), ('0414', '0414'), ('0424', '0424')], max_length=20, null=True)),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Celular')),
                ('tlf', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Telefonico')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('job', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ocupación Laboral')),
                ('updated', models.DateField(auto_now=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
    ]
