# Generated by Django 3.0.7 on 2021-12-09 01:14

import apps.entity.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('next_visit', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima visita')),
                ('status_notify', models.BooleanField(default=True, verbose_name='Notificador')),
                ('dni', models.CharField(max_length=8, unique=True, verbose_name='Cedula')),
                ('gender', models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15)),
                ('type_name', models.CharField(choices=[('V-', 'V-'), ('J-', 'J-'), ('E-', 'E-')], default='V-', max_length=10)),
                ('first_name', models.CharField(max_length=40, verbose_name='Nombres')),
                ('last_name', models.CharField(max_length=40, verbose_name='Apellidos')),
                ('address', models.CharField(blank=True, max_length=100, null=True, verbose_name='Direccion Habitacional')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Celular')),
                ('tlf', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Telefonico')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('fechaa', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('next_visit', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima visita')),
                ('status_notify', models.BooleanField(default=True, verbose_name='Notificador')),
                ('name', models.CharField(max_length=40, verbose_name='Nombres')),
                ('rif', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='RIF')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Celular')),
                ('tlf', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Telefonico')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('next_visit', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima visita')),
                ('status_notify', models.BooleanField(default=True, verbose_name='Notificador')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('date_nac', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('gender', models.CharField(choices=[('Hembra', 'Hembra'), ('Macho', 'Macho')], default='Hembra', max_length=20)),
                ('race', models.CharField(max_length=50, verbose_name='Raza')),
                ('weight', models.FloatField(default=0, max_length=10, verbose_name='Peso')),
                ('specie', models.CharField(choices=[('Gato', 'Gato'), ('Perro', 'Perro'), ('oveja', 'oveja'), ('cerdo', 'cerdo'), ('vaca', 'vaca'), ('cabra', 'cabra'), ('toro', 'toro'), ('gallo', 'gallo'), ('gallina', 'gallina'), ('alce', 'alce'), ('burro', 'burro')], default='Gato', max_length=50)),
                ('date_up', models.DateField(verbose_name='Fecha visita')),
                ('substitute', models.CharField(blank=True, max_length=150, null=True, verbose_name='Suplente')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Client', verbose_name='Propietario')),
            ],
            options={
                'verbose_name': 'Mascota',
                'verbose_name_plural': 'Mascotas',
                'ordering': ['id'],
            },
        ),
    ]
