# Generated by Django 3.0.7 on 2021-04-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='job',
        ),
        migrations.AlterField(
            model_name='client',
            name='co_mobile',
            field=models.CharField(blank=True, choices=[('0412', '0412'), ('0416', '0416'), ('0426', '0426'), ('0414', '0414'), ('0424', '0424')], max_length=20, null=True, verbose_name='Codigo de area'),
        ),
        migrations.AlterField(
            model_name='client',
            name='gender',
            field=models.CharField(choices=[('Masculino', 'Masculino'), ('Femenino', 'Femenino')], max_length=15),
        ),
    ]
