# Generated by Django 3.0.7 on 2021-04-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0002_auto_20210412_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='co_mobile',
        ),
    ]
