# Generated by Django 3.0.7 on 2021-04-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0003_remove_client_co_mobile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='Cliente',
        ),
    ]
