# Generated by Django 3.0.7 on 2021-04-12 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0004_auto_20210412_1227'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Client',
        ),
    ]
