# Generated by Django 3.0.7 on 2021-04-12 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0005_auto_20210412_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Fecha de edición'),
        ),
    ]
