# Generated by Django 3.0.7 on 2021-04-12 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0006_auto_20210412_1558'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='updated',
            new_name='fechaa',
        ),
    ]
