# Generated by Django 3.0.7 on 2021-04-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0008_auto_20210413_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fechaa',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de edición'),
        ),
    ]
