# Generated by Django 3.0.7 on 2021-04-13 14:02

import apps.entity.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0009_auto_20210413_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('name', models.CharField(max_length=40, verbose_name='Nombres')),
                ('rif', models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='RIF')),
                ('mobile', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Celular')),
                ('tlf', models.CharField(blank=True, max_length=11, null=True, verbose_name='Número de Telefonico')),
                ('Email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Correo Electronico')),
                ('date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de edición')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
    ]
