# Generated by Django 3.0.7 on 2021-04-14 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0012_auto_20210414_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='fechaa',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de edición'),
        ),
    ]
