# Generated by Django 3.0.7 on 2021-04-14 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0013_auto_20210414_0203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Client', verbose_name='Propietario'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='substitute',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Suplente'),
        ),
    ]
