# Generated by Django 3.0.7 on 2021-04-14 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entity', '0014_auto_20210414_0839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='date_up',
            field=models.DateField(verbose_name='Fecha visita'),
        ),
    ]
