<<<<<<< HEAD
# Generated by Django 3.0.7 on 2021-12-09 01:13
=======
# Generated by Django 3.0.7 on 2021-11-30 00:58
>>>>>>> b0891a40af8565bd3fc0e1b635d55a867dbce1e5

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='DollarStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField(default=True, verbose_name='Estado del bolivar en dolares')),
            ],
            options={
                'verbose_name': 'Estado del Dolar',
                'verbose_name_plural': 'Estado del Dolar',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
=======
>>>>>>> b0891a40af8565bd3fc0e1b635d55a867dbce1e5
            name='NotificationStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado de Notificación')),
            ],
            options={
                'verbose_name': 'Estado de Notificación',
                'verbose_name_plural': 'Estado de Notificación',
                'ordering': ['id'],
            },
        ),
    ]
