# Generated by Django 3.0.7 on 2021-11-02 21:40

import apps.entity.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('next_visit', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima visita')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Fecha')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('iva', models.FloatField(default=0, verbose_name='IVA')),
                ('sub_total', models.FloatField(default=0, verbose_name='Sub Total')),
                ('type_bs', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta')], max_length=30, verbose_name='Tipo')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Client', verbose_name='Cliente')),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra_Venta',
                'verbose_name_plural': 'Compras_Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ChildProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('next_visit', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima visita')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('price_buy', models.FloatField(default=0, verbose_name='Precio Compra')),
                ('price_sale', models.FloatField(default=0, verbose_name='Precio Venta')),
                ('date_conquered', models.DateField(verbose_name='Vencimiento')),
                ('profit', models.FloatField(default=0, verbose_name='Ganancia')),
            ],
            options={
                'verbose_name': 'Cantidad_Producto',
                'verbose_name_plural': 'Cantidad_Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('next_visit', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima visita')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('stock', models.IntegerField(blank=True, default=0, null=True, verbose_name='Cantidad')),
                ('num_sales', models.IntegerField(blank=True, default=0, null=True, verbose_name='Vendidos')),
                ('type_stock', models.CharField(choices=[('cantidad', 'cantidad'), ('tableta', 'tableta'), ('cc', 'cc'), ('litro', 'litro')], max_length=40, verbose_name='Unidad Medida')),
                ('quantity', models.FloatField(blank=True, default=0, null=True, verbose_name='Cantidad de medidad')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detail_BS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('next_visit', models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Proxima visita')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('profit', models.FloatField(default=0, verbose_name='Ganancia')),
                ('buy_sale', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Buy_Sale', verbose_name='Compra Venta')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.ChildProduct', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Detalle_CV',
                'verbose_name_plural': 'Detalles_CV',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='childproduct',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Product', verbose_name='Producto'),
        ),
    ]
