# Generated by Django 3.0.7 on 2021-04-14 13:39

import apps.entity.models
import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('health', '0001_initial'),
        ('entity', '0014_auto_20210414_0839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buy_Sale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('date', models.DateTimeField(default=datetime.datetime(2021, 4, 14, 8, 39, 42, 623805), verbose_name='Fecha')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('type_bs', models.CharField(choices=[('Compra', 'Compra'), ('Venta', 'Venta')], max_length=30, verbose_name='Tipo')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Client', verbose_name='Cliente')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entity.Provider', verbose_name='Proveedor')),
            ],
            options={
                'verbose_name': 'Compra_Venta',
                'verbose_name_plural': 'Compras_Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('name', models.CharField(max_length=50, verbose_name='Nombre Producto')),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('price_buy', models.FloatField(default=0, verbose_name='Precio Compra')),
                ('price_sale', models.FloatField(default=0, verbose_name='Precio Venta')),
                ('date_conquered', models.DateField(verbose_name='Vencimiento')),
                ('profit', models.FloatField(default=0, verbose_name='Ganancia')),
                ('num_sales', models.IntegerField(default=0, verbose_name='Vendidos')),
                ('type_stock', models.CharField(choices=[('cantidad', 'cantidad'), ('tableta', 'tableta'), ('cc', 'cc'), ('litro', 'litro')], max_length=40, verbose_name='Unidad Medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Detail_BS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Estado')),
                ('urlsecret', models.SlugField(blank=True, default=apps.entity.models.my_urlsecret, null=True)),
                ('stock', models.IntegerField(default=0, verbose_name='Cantidad')),
                ('price', models.FloatField(default=0, verbose_name='Precio')),
                ('total', models.FloatField(default=0, verbose_name='Total')),
                ('profit', models.FloatField(default=0, verbose_name='Ganancia')),
                ('buy_sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Buy_Sale', verbose_name='Compra Venta')),
                ('consul', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Consultation', verbose_name='Consulta')),
                ('parasite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Parasite', verbose_name='Desparasitacion')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cashier.Product', verbose_name='Producto')),
                ('vaccine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='health.Vaccine', verbose_name='Vacunacion')),
            ],
            options={
                'verbose_name': 'Detalle_CV',
                'verbose_name_plural': 'Detalles_CV',
                'ordering': ['id'],
            },
        ),
    ]
