# Generated by Django 3.0.7 on 2021-12-12 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detail_bs',
            name='price_buy',
            field=models.FloatField(default=0, verbose_name='Precio Compra'),
        ),
        migrations.AddField(
            model_name='detail_bs',
            name='price_sale',
            field=models.FloatField(default=0, verbose_name='Precio Venta'),
        ),
    ]
