# Generated by Django 3.0.7 on 2021-12-01 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0002_buy_sale_total_bs'),
    ]

    operations = [
        migrations.AddField(
            model_name='buy_sale',
            name='price_dollar',
            field=models.FloatField(default=0, verbose_name='Precio dolar'),
        ),
    ]
