# Generated by Django 3.0.7 on 2021-04-14 13:49

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        ('entity', '0014_auto_20210414_0839'),
        ('cashier', '0004_auto_20210414_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_sale',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Client', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='buy_sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 8, 49, 19, 378896), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='buy_sale',
            name='provider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Provider', verbose_name='Proveedor'),
        ),
        migrations.AlterField(
            model_name='detail_bs',
            name='buy_sale',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Buy_Sale', verbose_name='Compra Venta'),
        ),
        migrations.AlterField(
            model_name='detail_bs',
            name='consul',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Consultation', verbose_name='Consulta'),
        ),
        migrations.AlterField(
            model_name='detail_bs',
            name='parasite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Parasite', verbose_name='Desparasitacion'),
        ),
        migrations.AlterField(
            model_name='detail_bs',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='cashier.Product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='detail_bs',
            name='vaccine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='health.Vaccine', verbose_name='Vacunacion'),
        ),
    ]
