# Generated by Django 3.0.7 on 2021-04-14 19:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0005_auto_20210414_0849'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy_sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 14, 14, 57, 35, 647506), verbose_name='Fecha'),
        ),
    ]
