# Generated by Django 3.0.7 on 2021-04-15 17:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0007_auto_20210415_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.FloatField(default=0, verbose_name='Cantidad de medidad'),
        ),
        migrations.AlterField(
            model_name='buy_sale',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 15, 12, 32, 52, 630506), verbose_name='Fecha'),
        ),
    ]
