# Generated by Django 3.0.7 on 2021-06-01 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cashier', '0010_auto_20210418_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detail_bs',
            name='consul',
        ),
        migrations.RemoveField(
            model_name='detail_bs',
            name='parasite',
        ),
        migrations.RemoveField(
            model_name='detail_bs',
            name='vaccine',
        ),
    ]
